import { definePortableCollection } from '@vertexade/platform-extension-sdk'

export const azureWorkItemsSurface = definePortableCollection({
  id: 'work-items',
  title: 'Azure Boards work items',
  description: 'Browse the active sprint, update item state, and launch implementation.',
  source: {
    path: '/board',
    configuredPath: 'configured',
    itemsPath: 'portable_items',
  },
  item: {
    idPath: 'id',
    titlePath: 'portable_title',
    fieldsPath: 'portable_fields',
    fieldNamePath: 'name',
    fieldValuePath: 'value',
    fieldStylePath: 'style',
    fieldPlacementPath: 'placement',
    fieldImagePath: 'image_url',
    relationItemsPath: 'relation.items',
    relationIdPath: 'id',
    relationTitlePath: 'title',
    relationUrlPath: 'url',
    relationImagePath: 'image_url',
  },
  views: {
    list: true,
    default: 'kanban',
    pagination: { enabled: true, pageSize: 12 },
    kanban: {
      enabled: true,
      groupFieldsPath: 'portable_group_fields',
      groupFieldNamePath: 'field',
      defaultField: 'Board column',
      groupOrderPath: 'taskboard_columns',
      groupOrderValuePath: 'name',
      groupOrderEntriesPath: 'portable_group_order',
      groupOrderEntryFieldPath: 'field',
      groupOrderEntryValuePath: 'value',
      swimlanes: {
        defaultOption: 'story',
        nestedByDefault: true,
        options: [
          { id: 'none', label: 'No swimlanes', kind: 'none' },
          {
            id: 'story',
            label: 'Story',
            kind: 'hierarchy',
            field: 'Type',
            anchorValues: ['User Story', 'Product Backlog Item'],
            nestedLabel: 'Subtasks',
          },
          {
            id: 'feature',
            label: 'Feature',
            kind: 'hierarchy',
            field: 'Type',
            anchorValues: ['Feature', 'Epic'],
            nestedAnchorValues: ['User Story', 'Product Backlog Item'],
          },
          { id: 'assignee', label: 'Assignee', kind: 'field', field: 'Assigned' },
          { id: 'type', label: 'Work-item type', kind: 'field', field: 'Type' },
        ],
      },
    },
    hierarchy: { parentIdPath: 'parent_id' },
  },
  sourceControls: [
    {
      id: 'iteration',
      label: 'Sprint',
      queryParameter: 'iteration',
      optionsPath: 'iterations',
      optionValuePath: 'path',
      optionLabelPath: 'name',
      selectedPath: 'selected_iteration',
    },
  ],
  facets: [
    { id: 'type', label: 'Types', field: 'Type' },
    { id: 'state', label: 'States', field: 'State' },
    { id: 'assigned', label: 'Assignees', field: 'Assigned' },
    { id: 'area', label: 'Areas', field: 'Area' },
    { id: 'tags', label: 'Tags', field: 'Tags' },
  ],
  collectionActionsPath: 'portable_collection_actions',
  itemActionsPath: 'portable_actions',
  detail: {
    source: { path: '/items/{id}' },
    titlePath: 'title',
    sections: [
      { id: 'description', title: 'Description', kind: 'markdown', path: 'description' },
      {
        id: 'acceptance',
        title: 'Acceptance criteria',
        kind: 'markdown',
        path: 'acceptance_criteria',
      },
      { id: 'children', title: 'Child work', kind: 'list', path: 'children' },
      { id: 'activity', title: 'Activity', kind: 'timeline', path: 'portable_activity' },
    ],
  },
  actions: [
    {
      id: 'start-work',
      label: 'Start Work',
      description: 'Launch implementation work from this Azure Boards item.',
      method: 'POST',
      path: '/items/{id}/thread',
      inputs: [
        {
          name: 'repository_id',
          label: 'Repository',
          type: 'select',
          required: true,
          optionsPath: 'repositories',
          optionValuePath: 'id',
          optionLabelPath: 'full_name',
        },
        { name: 'create_pr', label: 'Create a pull request', type: 'boolean', defaultValue: true },
      ],
      successMessage: 'Work started from the Azure Boards item.',
      intent: 'launch-work',
    },
    {
      id: 'change-state',
      label: 'Change State',
      description: 'Move this item to another valid Azure Boards state.',
      method: 'PATCH',
      path: '/items/{id}/state',
      inputs: [
        {
          name: 'state',
          label: 'State',
          type: 'select',
          required: true,
          optionsSource: 'item',
          optionsPath: 'state_options',
          optionValuePath: 'id',
          optionLabelPath: 'name',
        },
      ],
      successMessage: 'Azure Boards item state updated.',
    },
  ],
  setup: {
    message: 'Connect an Azure DevOps organization and project before using this surface.',
    settingsSurfaceId: 'settings',
  },
  refresh: {
    eventPrefixes: ['azure_'],
  },
})
