import { definePortableCollection } from '@vertexade/platform-extension-sdk'

export const linearIssuesSurface = definePortableCollection({
  id: 'issues',
  title: 'Linear issues',
  description: 'Browse planning work, update issue state, and launch implementation.',
  source: {
    path: '/board',
    configuredPath: 'configured',
    itemsPath: 'issues',
  },
  item: {
    idPath: 'id',
    titlePath: 'portable_title',
    fieldsPath: 'portable_fields',
    fieldNamePath: 'name',
    fieldValuePath: 'value',
    fieldStylePath: 'style',
    fieldPlacementPath: 'placement',
    relationItemsPath: 'relation.items',
    relationIdPath: 'id',
    relationTitlePath: 'title',
    relationUrlPath: 'url',
  },
  views: {
    list: true,
    kanban: {
      enabled: true,
      groupFieldsPath: 'portable_group_fields',
      groupFieldNamePath: 'field',
    },
  },
  facets: [
    { id: 'team', label: 'Teams', field: 'Team' },
    { id: 'project', label: 'Projects', field: 'Project' },
    { id: 'state', label: 'States', field: 'State' },
  ],
  collectionActions: [
    {
      id: 'create-issue',
      label: 'New issue',
      description: 'Create a Linear issue in one of the configured teams.',
      method: 'POST',
      path: '/issues',
      inputs: [
        { name: 'title', label: 'Title', type: 'text', required: true },
        { name: 'description', label: 'Description', type: 'textarea' },
        {
          name: 'team_id',
          label: 'Team',
          type: 'select',
          required: true,
          optionsPath: 'teams',
          optionValuePath: 'id',
          optionLabelPath: 'name',
        },
        {
          name: 'project_id',
          label: 'Project',
          type: 'select',
          optionsPath: 'portable_projects',
          optionValuePath: 'id',
          optionLabelPath: 'name',
          optionsFilterInput: 'team_id',
          optionsFilterPath: 'team_id',
        },
        {
          name: 'priority',
          label: 'Priority',
          type: 'select',
          defaultValue: '0',
          options: [
            { value: '0', label: 'No priority' },
            { value: '1', label: 'Urgent' },
            { value: '2', label: 'High' },
            { value: '3', label: 'Normal' },
            { value: '4', label: 'Low' },
          ],
        },
      ],
      successMessage: 'Linear issue created.',
    },
  ],
  actions: [
    {
      id: 'start-work',
      label: 'Start Work',
      description: 'Launch implementation work from this Linear issue.',
      method: 'POST',
      path: '/issues/{id}/thread',
      inputs: [
        {
          name: 'repository_id',
          label: 'Repository',
          type: 'select',
          required: true,
          optionsPath: 'repositories',
          optionValuePath: 'id',
          optionLabelPath: 'full_name',
        },
        { name: 'instruction', label: 'Additional instruction', type: 'text' },
        { name: 'create_pr', label: 'Create a pull request', type: 'boolean', defaultValue: true },
      ],
      successMessage: 'Work started from the Linear issue.',
      intent: 'launch-work',
    },
    {
      id: 'change-state',
      label: 'Change State',
      description: 'Move this issue to another Linear workflow state.',
      method: 'PATCH',
      path: '/issues/{id}',
      inputs: [
        {
          name: 'state_id',
          label: 'State',
          type: 'select',
          required: true,
          optionsSource: 'item',
          optionsPath: 'state_options',
          optionValuePath: 'id',
          optionLabelPath: 'name',
        },
      ],
      successMessage: 'Linear issue state updated.',
    },
  ],
  setup: {
    message: 'Connect Linear and select at least one team before using this surface.',
    settingsSurfaceId: 'settings',
  },
  refresh: {
    eventPrefixes: ['linear_'],
  },
})
