/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PullRequestsRouteImport } from './routes/pull-requests'
import { Route as MigrationsRouteImport } from './routes/migrations'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as ExtensionsIndexRouteImport } from './routes/extensions.index'
import { Route as WorkWorkKeyRouteImport } from './routes/work.$workKey'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads_.$threadId'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as PullRequestsRepoIdPrNumberRouteImport } from './routes/pull-requests_.$repoId.$prNumber'
import { Route as ExtensionsModuleIdSplatRouteImport } from './routes/extensions.$moduleId.$'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsRoute = PullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsRoute = MigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const ExtensionsIndexRoute = ExtensionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExtensionsRoute,
} as any)
const WorkWorkKeyRoute = WorkWorkKeyRouteImport.update({
  id: '/$workKey',
  path: '/$workKey',
  getParentRoute: () => WorkRoute,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads_/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsRepoIdPrNumberRoute =
  PullRequestsRepoIdPrNumberRouteImport.update({
    id: '/pull-requests_/$repoId/$prNumber',
    path: '/pull-requests/$repoId/$prNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExtensionsModuleIdSplatRoute = ExtensionsModuleIdSplatRouteImport.update({
  id: '/$moduleId/$',
  path: '/$moduleId/$',
  getParentRoute: () => ExtensionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/automations': typeof AutomationsRoute
  '/deployments': typeof DeploymentsRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/impact': typeof ImpactRoute
  '/inbox': typeof InboxRoute
  '/migrations': typeof MigrationsRoute
  '/pull-requests': typeof PullRequestsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/threads': typeof ThreadsRoute
  '/work': typeof WorkRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/work/$workKey': typeof WorkWorkKeyRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/extensions/$moduleId/$': typeof ExtensionsModuleIdSplatRoute
  '/pull-requests/$repoId/$prNumber': typeof PullRequestsRepoIdPrNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/automations': typeof AutomationsRoute
  '/deployments': typeof DeploymentsRoute
  '/impact': typeof ImpactRoute
  '/inbox': typeof InboxRoute
  '/migrations': typeof MigrationsRoute
  '/pull-requests': typeof PullRequestsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/threads': typeof ThreadsRoute
  '/api/$': typeof ApiSplatRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/work/$workKey': typeof WorkWorkKeyRoute
  '/extensions': typeof ExtensionsIndexRoute
  '/work': typeof WorkIndexRoute
  '/extensions/$moduleId/$': typeof ExtensionsModuleIdSplatRoute
  '/pull-requests/$repoId/$prNumber': typeof PullRequestsRepoIdPrNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/automations': typeof AutomationsRoute
  '/deployments': typeof DeploymentsRoute
  '/extensions': typeof ExtensionsRouteWithChildren
  '/impact': typeof ImpactRoute
  '/inbox': typeof InboxRoute
  '/migrations': typeof MigrationsRoute
  '/pull-requests': typeof PullRequestsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/threads': typeof ThreadsRoute
  '/work': typeof WorkRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/threads_/$threadId': typeof ThreadsThreadIdRoute
  '/work/$workKey': typeof WorkWorkKeyRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/extensions/$moduleId/$': typeof ExtensionsModuleIdSplatRoute
  '/pull-requests_/$repoId/$prNumber': typeof PullRequestsRepoIdPrNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/automations'
    | '/deployments'
    | '/extensions'
    | '/impact'
    | '/inbox'
    | '/migrations'
    | '/pull-requests'
    | '/settings'
    | '/setup'
    | '/threads'
    | '/work'
    | '/api/$'
    | '/threads/$threadId'
    | '/work/$workKey'
    | '/extensions/'
    | '/work/'
    | '/extensions/$moduleId/$'
    | '/pull-requests/$repoId/$prNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/automations'
    | '/deployments'
    | '/impact'
    | '/inbox'
    | '/migrations'
    | '/pull-requests'
    | '/settings'
    | '/setup'
    | '/threads'
    | '/api/$'
    | '/threads/$threadId'
    | '/work/$workKey'
    | '/extensions'
    | '/work'
    | '/extensions/$moduleId/$'
    | '/pull-requests/$repoId/$prNumber'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/automations'
    | '/deployments'
    | '/extensions'
    | '/impact'
    | '/inbox'
    | '/migrations'
    | '/pull-requests'
    | '/settings'
    | '/setup'
    | '/threads'
    | '/work'
    | '/api/$'
    | '/threads_/$threadId'
    | '/work/$workKey'
    | '/extensions/'
    | '/work/'
    | '/extensions/$moduleId/$'
    | '/pull-requests_/$repoId/$prNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AutomationsRoute: typeof AutomationsRoute
  DeploymentsRoute: typeof DeploymentsRoute
  ExtensionsRoute: typeof ExtensionsRouteWithChildren
  ImpactRoute: typeof ImpactRoute
  InboxRoute: typeof InboxRoute
  MigrationsRoute: typeof MigrationsRoute
  PullRequestsRoute: typeof PullRequestsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ThreadsRoute: typeof ThreadsRoute
  WorkRoute: typeof WorkRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  PullRequestsRepoIdPrNumberRoute: typeof PullRequestsRepoIdPrNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests': {
      id: '/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof PullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations': {
      id: '/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof MigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/extensions/': {
      id: '/extensions/'
      path: '/'
      fullPath: '/extensions/'
      preLoaderRoute: typeof ExtensionsIndexRouteImport
      parentRoute: typeof ExtensionsRoute
    }
    '/work/$workKey': {
      id: '/work/$workKey'
      path: '/$workKey'
      fullPath: '/work/$workKey'
      preLoaderRoute: typeof WorkWorkKeyRouteImport
      parentRoute: typeof WorkRoute
    }
    '/threads_/$threadId': {
      id: '/threads_/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests_/$repoId/$prNumber': {
      id: '/pull-requests_/$repoId/$prNumber'
      path: '/pull-requests/$repoId/$prNumber'
      fullPath: '/pull-requests/$repoId/$prNumber'
      preLoaderRoute: typeof PullRequestsRepoIdPrNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/$moduleId/$': {
      id: '/extensions/$moduleId/$'
      path: '/$moduleId/$'
      fullPath: '/extensions/$moduleId/$'
      preLoaderRoute: typeof ExtensionsModuleIdSplatRouteImport
      parentRoute: typeof ExtensionsRoute
    }
  }
}

interface ExtensionsRouteChildren {
  ExtensionsIndexRoute: typeof ExtensionsIndexRoute
  ExtensionsModuleIdSplatRoute: typeof ExtensionsModuleIdSplatRoute
}

const ExtensionsRouteChildren: ExtensionsRouteChildren = {
  ExtensionsIndexRoute: ExtensionsIndexRoute,
  ExtensionsModuleIdSplatRoute: ExtensionsModuleIdSplatRoute,
}

const ExtensionsRouteWithChildren = ExtensionsRoute._addFileChildren(
  ExtensionsRouteChildren,
)

interface WorkRouteChildren {
  WorkWorkKeyRoute: typeof WorkWorkKeyRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkWorkKeyRoute: WorkWorkKeyRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  AutomationsRoute: AutomationsRoute,
  DeploymentsRoute: DeploymentsRoute,
  ExtensionsRoute: ExtensionsRouteWithChildren,
  ImpactRoute: ImpactRoute,
  InboxRoute: InboxRoute,
  MigrationsRoute: MigrationsRoute,
  PullRequestsRoute: PullRequestsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ThreadsRoute: ThreadsRoute,
  WorkRoute: WorkRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  PullRequestsRepoIdPrNumberRoute: PullRequestsRepoIdPrNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
