import type { Job, WorkItem } from '@vertexade/ui/lib/dashboard-types'

export function workItem(id: number, overrides: Partial<WorkItem> = {}): WorkItem {
  return {
    id,
    key: `W-${String(id).padStart(4, '0')}`,
    title: `Work ${id}`,
    description: '',
    kind: 'implementation',
    state: 'backlog',
    state_override: null,
    state_override_reason: null,
    priority: 'normal',
    owner: null,
    primary_repository_id: null,
    primary_repository_name: null,
    repository_names: [],
    attention: null,
    sequential_execution: false,
    archived_at: null,
    created_at: `2026-07-${String(id).padStart(2, '0')} 09:00:00`,
    updated_at: `2026-07-${String(id).padStart(2, '0')} 10:00:00`,
    resources: [],
    threads: [],
    events: [],
    relations: [],
    context_transfers: [],
    ...overrides,
  }
}

export function job(id: number, overrides: Partial<Job> = {}): Job {
  return {
    id,
    repo_id: 1,
    full_name: 'example/platform',
    pr_number: 0,
    status: 'completed',
    thread_id: `thread-${id}`,
    thread_url: null,
    agent_id: 'codex',
    agent_name: 'Codex',
    can_steer: true,
    worktree_path: `/tmp/work-${id}`,
    head_sha: null,
    latest_activity: null,
    activity_at: `2026-07-${String(id).padStart(2, '0')} 10:00:00`,
    created_at: `2026-07-${String(id).padStart(2, '0')} 09:00:00`,
    finished_at: null,
    diff_files: null,
    diff_additions: 0,
    diff_deletions: 0,
    input_questions: null,
    kind: 'task',
    source_job_id: null,
    task_title: null,
    branch_name: null,
    linked_pr_number: null,
    linked_pr_url: null,
    archived_at: null,
    pr_merged_at: null,
    pr_closed_at: null,
    review_phase: null,
    review_phase_started_at: null,
    review_details: null,
    review_summary: null,
    agent_model: null,
    agent_reasoning_effort: null,
    work_item_id: null,
    ...overrides,
  }
}
