import {
  Blocks,
  Boxes,
  BriefcaseBusiness,
  GitFork,
  GitPullRequest,
  Inbox,
  MessagesSquare,
  Rocket,
  Settings,
  Workflow,
  Wrench,
} from 'lucide-react'
import type { NavItem } from './app-nav'

export const coreItems = [
  {
    to: '/',
    label: 'Focus',
    description: 'Decide what needs your attention next',
    icon: Inbox,
    group: 'Workspace',
  },
  {
    to: '/work',
    label: 'Work',
    description: 'Plan and manage durable outcomes',
    icon: BriefcaseBusiness,
    group: 'Workspace',
  },
  {
    to: '/threads',
    label: 'Agents',
    description: 'Follow active runs, decisions, and results',
    icon: MessagesSquare,
    group: 'Workspace',
  },
  {
    to: '/architecture',
    label: 'Architecture',
    description: 'Browse repository boundaries, contracts, and decisions',
    icon: Boxes,
    group: 'Workspace',
  },
  {
    to: '/pull-requests',
    label: 'Pull requests',
    compactLabel: 'PRs',
    description: 'Review code and move it toward merge',
    icon: GitPullRequest,
    group: 'Operations',
  },
  {
    to: '/deployments',
    label: 'Delivery',
    description: 'Follow releases, services, and environments',
    icon: Rocket,
    group: 'Operations',
  },
  {
    to: '/automations',
    label: 'Automations',
    description: 'Build and monitor repeatable flows',
    icon: Workflow,
    group: 'Operations',
  },
  {
    to: '/migrations',
    label: 'Migrations',
    description: 'Roll out versioned changes across repositories and servers',
    icon: GitFork,
    group: 'Operations',
  },
  {
    to: '/extensions',
    label: 'Extensions',
    description: 'Connect tools and manage integrations',
    icon: Blocks,
    group: 'System',
  },
  {
    to: '/setup',
    label: 'System health',
    description: 'Check prerequisites, connections, and services',
    icon: Wrench,
    group: 'System',
  },
  {
    to: '/settings',
    label: 'Settings',
    description: 'Workspace defaults, repositories, agents, and appearance',
    icon: Settings,
    group: 'System',
  },
] as const satisfies readonly NavItem[]
