import { definePortableSettings } from '@vertexade/platform-extension-sdk'

export const airtableSettings = definePortableSettings({
  id: 'settings',
  title: 'Airtable connection',
  description: 'Connect a base, shape its cards, and optionally let VertexADE manage live inbound synchronization.',
  source: { path: '/settings', configuredPath: 'configured' },
  fields: [
    {
      name: 'token',
      label: 'Personal access token',
      type: 'password',
      storedPath: 'has_token',
      required: true,
      placeholder: 'pat…',
    },
    { name: 'base_id', label: 'Base ID', type: 'text', required: true },
    { name: 'view', label: 'View', type: 'text' },
    {
      name: 'table_id',
      label: 'Table',
      type: 'select',
      required: true,
      optionsAction: 'detect',
      optionsPath: 'tables',
      optionValuePath: 'id',
      optionLabelPath: 'name',
    },
    {
      name: 'title_field',
      label: 'Card title',
      type: 'select',
      required: true,
      optionsAction: 'detect',
      optionsPath: 'fields',
      optionValuePath: 'name',
      optionLabelPath: 'label',
      optionsFilterInput: 'table_id',
      optionsFilterPath: 'table_id',
    },
    {
      name: 'card_fields',
      label: 'Card fields',
      type: 'object-list',
      valuePath: 'card_fields',
      addLabel: 'Add card field',
      allowReorder: true,
      fields: [
        {
          name: 'field',
          label: 'Field',
          type: 'select',
          required: true,
          optionsAction: 'detect',
          optionsPath: 'fields',
          optionValuePath: 'name',
          optionLabelPath: 'label',
          optionsFilterInput: 'table_id',
          optionsFilterPath: 'table_id',
        },
        {
          name: 'style',
          label: 'Style',
          type: 'select',
          defaultValue: 'text',
          options: [
            { value: 'text', label: 'Text' },
            { value: 'badge', label: 'Badge' },
            { value: 'date', label: 'Date' },
            { value: 'person', label: 'Person' },
            { value: 'links', label: 'Linked records' },
          ],
        },
        {
          name: 'placement',
          label: 'Placement',
          type: 'select',
          defaultValue: 'card',
          options: [
            { value: 'card', label: 'Card' },
            { value: 'detail', label: 'Detail' },
          ],
        },
        { name: 'resolve', label: 'Resolve linked records', type: 'boolean' },
      ],
    },
    {
      name: 'live_sync',
      label: 'Enable live sync',
      type: 'boolean',
      description: 'Creates and manages an authenticated Airtable webhook for this table.',
    },
    {
      name: 'public_url',
      label: 'Public VertexADE URL',
      type: 'text',
      required: true,
      placeholder: 'https://vertexade.example.com',
      description: 'Airtable must be able to reach this HTTPS origin. The extension adds /api/extensions/airtable/webhook automatically.',
      visibleWhen: { input: 'live_sync', equals: true },
    },
  ],
  sections: [
    { id: 'connection', title: 'Connection', fields: ['token', 'base_id', 'view'] },
    { id: 'mapping', title: 'Record mapping', fields: ['table_id', 'title_field', 'card_fields'] },
    {
      id: 'two-way-sync',
      title: 'Two-way sync',
      description: 'Verified Airtable notifications refresh only this extension board.',
      fields: ['live_sync', 'public_url'],
    },
  ],
  submit: {
    method: 'POST',
    path: '/settings',
    label: 'Save connection',
    successMessage: 'Airtable connection saved.',
  },
  actions: [
    {
      id: 'detect',
      label: 'Discover base structure',
      method: 'POST',
      path: '/detect',
      intent: 'discover',
      includeFields: ['token', 'base_id'],
    },
    {
      id: 'reset',
      label: 'Remove connection',
      method: 'DELETE',
      path: '/settings',
      intent: 'reset',
      confirm: {
        title: 'Remove Airtable connection?',
        description: 'The managed webhook will be removed before the encrypted Airtable connection is deleted.',
        confirmLabel: 'Remove connection',
        destructive: true,
      },
    },
  ],
})
