import { StyleSheet } from 'react-native'
import { colors, radii, spacing } from '@/theme'

export const mobileDetailStyles = StyleSheet.create({
  modal: {
    backgroundColor: colors.background,
    flex: 1,
    paddingTop: spacing.md,
  },
  detailBody: { flex: 1 },
  header: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
  },
  headerTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  heading: { flex: 1, gap: 4 },
  eyebrow: {
    color: colors.accent,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  title: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 26,
  },
  subtitle: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  headerBadges: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginTop: 3 },
  headerMetrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginTop: spacing.sm },
  headerMetric: {
    backgroundColor: 'rgba(8,11,16,0.68)',
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderWidth: 1,
    flexGrow: 1,
    gap: 2,
    minWidth: 108,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  headerMetricLabel: { color: colors.muted, fontSize: 8, fontWeight: '800', letterSpacing: 0.8 },
  headerMetricValue: { color: colors.text, fontSize: 11, fontWeight: '700' },
  close: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: 4,
  },
  tabs: { gap: spacing.sm },
  tab: {
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  tabActive: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  tabText: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  tabTextActive: { color: colors.accent },
  content: { gap: spacing.md, padding: spacing.md, paddingBottom: 80 },
  outcome: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    borderLeftWidth: 3,
    gap: 3,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  outcomeTitle: { color: colors.text, fontSize: 12, fontWeight: '800' },
  outcomeText: { color: colors.muted, fontSize: 11, lineHeight: 16 },
  outcomeActive: { backgroundColor: '#111b2b', borderLeftColor: colors.info },
  outcomeSuccess: { backgroundColor: '#0d211d', borderLeftColor: colors.accent },
  outcomeWarning: { backgroundColor: '#261e10', borderLeftColor: colors.warning },
  outcomeDanger: { backgroundColor: '#291419', borderLeftColor: colors.danger },
  outcomeNeutral: { backgroundColor: colors.surface, borderLeftColor: colors.border },
  section: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  sectionTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
  sectionMeta: { color: colors.muted, fontSize: 10 },
  body: { color: colors.text, fontSize: 13, lineHeight: 20 },
  markdown: { minHeight: 20, width: '100%' },
  diffViewer: {
    backgroundColor: '#05070a',
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    height: 560,
    overflow: 'hidden',
  },
  diffNativeView: { flex: 1, width: '100%' },
  muted: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  label: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
  },
  value: { color: colors.text, fontSize: 13, lineHeight: 18 },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  metric: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.md,
    gap: 3,
    minWidth: 78,
    padding: spacing.sm,
  },
  metricValue: { color: colors.text, fontSize: 16, fontWeight: '800' },
  metricLabel: { color: colors.muted, fontSize: 9, fontWeight: '700' },
  badges: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  badge: {
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    color: colors.accent,
    fontSize: 10,
    fontWeight: '700',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  badgeDanger: { backgroundColor: '#3a1b22', color: colors.danger },
  row: {
    borderTopColor: colors.border,
    borderTopWidth: 1,
    gap: 5,
    paddingTop: spacing.md,
  },
  rowFirst: { borderTopWidth: 0, paddingTop: 0 },
  rowTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  rowText: { color: colors.muted, fontSize: 11, lineHeight: 17 },
  rowMeta: { color: colors.accent, fontSize: 9, fontWeight: '700' },
  eventHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  eventMarker: { backgroundColor: colors.accentSoft, borderRadius: 999, height: 8, width: 8 },
  eventTitle: { color: colors.text, flex: 1, fontSize: 13, fontWeight: '700' },
  queueCard: { backgroundColor: colors.surfaceRaised, borderRadius: radii.md, gap: spacing.sm, padding: spacing.md },
  fileRow: {
    alignItems: 'center',
    borderTopColor: colors.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  filePath: {
    color: colors.text,
    flex: 1,
    fontFamily: 'monospace',
    fontSize: 11,
  },
  additions: { color: colors.accent, fontSize: 10, fontWeight: '700' },
  deletions: { color: colors.danger, fontSize: 10, fontWeight: '700' },
  code: {
    backgroundColor: '#05070a',
    borderRadius: radii.md,
    color: '#c7d2df',
    fontFamily: 'monospace',
    fontSize: 10,
    lineHeight: 15,
    padding: spacing.md,
  },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  actionsSpread: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, justifyContent: 'space-between' },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  primaryButtonText: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  secondaryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  secondaryButtonText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  dangerButton: { borderColor: colors.danger },
  dangerButtonText: { color: colors.danger },
  input: {
    backgroundColor: colors.surfaceRaised,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    color: colors.text,
    fontSize: 13,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingVertical: 11,
  },
  textarea: { minHeight: 100, textAlignVertical: 'top' },
  compactTextarea: { minHeight: 72, textAlignVertical: 'top' },
  footer: {
    backgroundColor: colors.background,
    borderTopColor: colors.border,
    borderTopWidth: 1,
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  composerFrame: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  composerMeta: { color: colors.muted, flex: 1, fontSize: 10, lineHeight: 14 },
  footerActions: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, justifyContent: 'flex-end' },
  footerButton: { flex: 1 },
  actionModal: { backgroundColor: colors.background, flex: 1, paddingTop: spacing.lg },
  actionModalHeader: {
    alignItems: 'flex-start',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.lg,
  },
  actionModalContent: { gap: spacing.md, padding: spacing.lg, paddingBottom: spacing.xl },
  actionList: { gap: spacing.sm },
  actionOption: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 50,
    padding: spacing.md,
  },
  actionOptionCopy: { flex: 1, gap: 2 },
  actionOptionTitle: { color: colors.text, fontSize: 13, fontWeight: '800' },
  actionOptionText: { color: colors.muted, fontSize: 10, lineHeight: 15 },
  optionSelected: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  formGroup: { gap: spacing.sm },
  inputLabel: { color: colors.text, fontSize: 12, fontWeight: '800' },
  inputHint: { color: colors.muted, fontSize: 10, lineHeight: 15 },
  suggestion: { backgroundColor: colors.surfaceRaised, borderRadius: radii.md, gap: spacing.sm, padding: spacing.md },
  suggestionHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' },
  error: { color: colors.danger, fontSize: 12, lineHeight: 17 },
  notice: { color: colors.accent, fontSize: 12, lineHeight: 17 },
  state: {
    alignItems: 'center',
    flex: 1,
    gap: spacing.sm,
    justifyContent: 'center',
    padding: spacing.xl,
  },
  stateTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
  stateText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.7 },
})
