import { StyleSheet } from 'react-native'
import { colors, radii, spacing } from '@/theme'

export const mobileServerSettingsStyles = StyleSheet.create({
  screen: { backgroundColor: colors.background, flex: 1 },
  tabs: { backgroundColor: colors.surface, borderRadius: radii.md, flexDirection: 'row', gap: 2, marginHorizontal: spacing.md, padding: 3 },
  tab: { alignItems: 'center', borderCurve: 'continuous', borderRadius: radii.sm, flex: 1, justifyContent: 'center', minHeight: 34, paddingHorizontal: spacing.sm },
  tabActive: { backgroundColor: colors.surfaceRaised },
  tabText: { color: colors.muted, fontSize: 13, fontWeight: '500' },
  tabTextActive: { color: colors.text, fontWeight: '600' },
  content: { gap: spacing.sm, padding: spacing.md, paddingBottom: spacing.xl },
  state: { alignItems: 'center', flex: 1, gap: spacing.md, justifyContent: 'center', padding: spacing.xl },
  error: { color: colors.danger, textAlign: 'center' },
  heading: { gap: 4, marginBottom: spacing.sm },
  title: { color: colors.text, fontSize: 22, fontWeight: '700' },
  subtitle: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  form: { backgroundColor: colors.surface, borderCurve: 'continuous', borderRadius: radii.lg, gap: spacing.sm, padding: spacing.md },
  formTitle: { color: colors.text, fontSize: 13, fontWeight: '600' },
  input: { backgroundColor: colors.surfaceRaised, borderCurve: 'continuous', borderRadius: radii.md, color: colors.text, fontSize: 15, minHeight: 44, paddingHorizontal: spacing.md, paddingVertical: 10 },
  textarea: { minHeight: 90, textAlignVertical: 'top' },
  inline: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  flex: { flex: 1 },
  row: { alignItems: 'center', backgroundColor: colors.surface, borderCurve: 'continuous', borderRadius: radii.md, flexDirection: 'row', gap: spacing.sm, minHeight: 56, padding: spacing.sm },
  rowCopy: { flex: 1, gap: 3 },
  rowTitle: { color: colors.text, fontSize: 14, fontWeight: '600' },
  rowDetail: { color: colors.muted, fontSize: 11, lineHeight: 15 },
  action: { alignItems: 'center', borderCurve: 'continuous', borderRadius: radii.md, justifyContent: 'center', minHeight: 36, paddingHorizontal: spacing.sm },
  actionPrimary: { backgroundColor: colors.accent },
  actionText: { color: colors.accent, fontSize: 13, fontWeight: '600' },
  actionPrimaryText: { color: colors.ink },
  destructive: { color: colors.danger },
  actions: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, justifyContent: 'flex-end' },
  checklist: { borderColor: colors.border, borderRadius: radii.md, borderWidth: StyleSheet.hairlineWidth, gap: 2, padding: spacing.sm },
  checkRow: { alignItems: 'center', flexDirection: 'row', minHeight: 36 },
  checkmark: { color: colors.accent, fontSize: 17, fontWeight: '700', width: 24 },
  empty: { color: colors.muted, padding: spacing.lg, textAlign: 'center' },
})
