import { StyleSheet } from 'react-native'
import { colors, radii, spacing } from '@/theme'

export const mobileWorkspaceStyles = StyleSheet.create({
  screen: { backgroundColor: colors.background, flex: 1 },
  header: { borderBottomColor: colors.border, borderBottomWidth: 1, gap: spacing.md, paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.md },
  topRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  heading: { flex: 1, gap: 3 },
  eyebrow: { color: colors.accent, fontSize: 10, fontWeight: '800', letterSpacing: 1.5 },
  title: { color: colors.text, fontSize: 25, fontWeight: '800', letterSpacing: -0.6 },
  subtitle: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  createButton: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: radii.md, justifyContent: 'center', minHeight: 44, paddingHorizontal: spacing.md },
  createButtonText: { color: colors.ink, fontSize: 13, fontWeight: '800' },
  tabs: { gap: spacing.sm },
  tab: { alignItems: 'center', borderColor: colors.border, borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 6, minHeight: 40, paddingHorizontal: spacing.md },
  tabActive: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  tabText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  tabTextActive: { color: colors.accent },
  tabCount: { backgroundColor: colors.surfaceRaised, borderRadius: 999, color: colors.muted, fontSize: 10, overflow: 'hidden', paddingHorizontal: 6, paddingVertical: 2 },
  search: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.text, fontSize: 14, paddingHorizontal: spacing.md, paddingVertical: 11 },
  list: { gap: spacing.sm, padding: spacing.md, paddingBottom: 70 },
  statusBox: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, gap: spacing.sm, padding: spacing.md },
  notice: { color: colors.accent, fontSize: 12, lineHeight: 17 },
  error: { color: colors.danger, fontSize: 12, lineHeight: 17 },
  card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: spacing.sm, padding: spacing.md },
  cardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' },
  cardCopy: { flex: 1, gap: 4 },
  cardEyebrow: { color: colors.accent, fontSize: 9, fontWeight: '800', letterSpacing: 0.9 },
  cardTitle: { color: colors.text, fontSize: 15, fontWeight: '800', lineHeight: 20 },
  cardText: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  badge: { alignSelf: 'flex-start', backgroundColor: colors.accentSoft, borderRadius: 999, color: colors.accent, fontSize: 10, fontWeight: '800', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4 },
  badgeDanger: { backgroundColor: '#3a1b22', color: colors.danger },
  metadata: { color: colors.muted, fontSize: 10, lineHeight: 15 },
  cardActions: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  primaryButton: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: radii.md, justifyContent: 'center', minHeight: 40, paddingHorizontal: spacing.md },
  primaryButtonText: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  secondaryButton: { alignItems: 'center', borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, justifyContent: 'center', minHeight: 40, paddingHorizontal: spacing.md },
  secondaryButtonText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  empty: { alignItems: 'center', gap: spacing.sm, minHeight: 220, justifyContent: 'center', padding: spacing.xl },
  emptyTitle: { color: colors.text, fontSize: 16, fontWeight: '800', textAlign: 'center' },
  emptyText: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: 'center' },
  more: { gap: spacing.lg },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
  modal: { backgroundColor: colors.background, flex: 1, paddingTop: spacing.lg },
  modalHeader: { alignItems: 'flex-start', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between', padding: spacing.lg },
  modalHeading: { flex: 1, gap: 4 },
  modalEyebrow: { color: colors.accent, fontSize: 10, fontWeight: '800', letterSpacing: 1.5 },
  modalTitle: { color: colors.text, fontSize: 24, fontWeight: '800' },
  close: { color: colors.accent, fontSize: 14, fontWeight: '700' },
  modalContent: { gap: spacing.lg, padding: spacing.lg, paddingBottom: spacing.xl },
  inputGroup: { gap: spacing.sm },
  inputLabel: { color: colors.text, fontSize: 13, fontWeight: '800' },
  inputHint: { color: colors.muted, fontSize: 11, lineHeight: 16 },
  textArea: { minHeight: 120, textAlignVertical: 'top' },
  options: { gap: spacing.sm },
  option: { borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, gap: 3, minHeight: 44, padding: spacing.md },
  optionSelected: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  optionText: { color: colors.text, fontSize: 13, fontWeight: '700' },
  optionTextSelected: { color: colors.accent },
  optionMeta: { color: colors.muted, fontSize: 10 },
  switchRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  switchCopy: { flex: 1, gap: 3 },
  modalPrimary: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: radii.md, justifyContent: 'center', margin: spacing.lg, minHeight: 48 },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.72 },
})
