import { StyleSheet } from 'react-native'
import { colors, radii, spacing } from '@/theme'

export const mobileHomeStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.lg, gap: spacing.lg },
  hero: { paddingTop: spacing.md, gap: spacing.sm },
  eyebrow: { color: colors.accent, fontSize: 11, fontWeight: '800', letterSpacing: 1.8 },
  title: { color: colors.text, fontSize: 34, fontWeight: '800', letterSpacing: -1.1, lineHeight: 39 },
  subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  panel: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, padding: spacing.md, gap: spacing.sm },
  label: { color: colors.text, fontSize: 13, fontWeight: '700' },
  input: { backgroundColor: colors.surfaceRaised, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.text, fontSize: 15, paddingHorizontal: spacing.md, paddingVertical: 12 },
  primaryButton: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: radii.md, minHeight: 46, justifyContent: 'center' },
  primaryButtonText: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  warning: { color: colors.warning, fontSize: 11, lineHeight: 16 },
  error: { color: colors.danger, fontSize: 13, lineHeight: 19 },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.72 },
  section: { gap: spacing.sm },
  sectionTitle: { color: colors.text, fontSize: 19, fontWeight: '800' },
  sectionMeta: { color: colors.muted, fontSize: 12, marginTop: -6 },
  moduleCard: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, flexDirection: 'row', gap: spacing.md, padding: spacing.md },
  moduleIcon: { alignItems: 'center', backgroundColor: colors.accentSoft, borderRadius: 13, height: 42, justifyContent: 'center', width: 42 },
  moduleIconText: { color: colors.accent, fontSize: 18, fontWeight: '800' },
  moduleCopy: { flex: 1, gap: 3 },
  moduleTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
  moduleDescription: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  moduleMeta: { color: colors.accent, fontSize: 10, fontWeight: '700', marginTop: 2 },
  chevron: { color: colors.muted, fontSize: 28 },
  empty: { alignItems: 'center', borderColor: colors.border, borderRadius: radii.lg, borderStyle: 'dashed', borderWidth: 1, gap: 5, padding: spacing.xl },
  emptyTitle: { color: colors.text, fontSize: 14, fontWeight: '700' },
  emptyText: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
})
