import { StyleSheet } from 'react-native'
import { colors, radii, spacing } from '@/theme'

export const mobileDetailStyles = StyleSheet.create({
  modal: {
    backgroundColor: colors.background,
    flex: 1,
    paddingTop: 0,
  },
  detailBody: { flex: 1 },
  header: {
    backgroundColor: colors.background,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: spacing.md,
    paddingBottom: spacing.sm,
  },
  headerCompact: { gap: spacing.xs, paddingBottom: spacing.xs },
  headerTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  heading: { flex: 1, gap: 4 },
  eyebrow: {
    color: colors.accent,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  title: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 34,
  },
  titleCompact: { fontSize: 18, lineHeight: 24 },
  subtitle: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  headerBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: 3,
  },
  headerMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  headerMetric: {
    backgroundColor: 'rgba(8,11,16,0.68)',
    borderColor: colors.border,
    borderRadius: radii.sm,
    borderWidth: 1,
    flexGrow: 1,
    gap: 2,
    minWidth: 108,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  headerMetricLabel: {
    color: colors.muted,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  headerMetricValue: { color: colors.text, fontSize: 11, fontWeight: '700' },
  entitySummary: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between', paddingHorizontal: spacing.md },
  entitySummaryMain: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: spacing.sm, minWidth: 0 },
  entityStatus: { backgroundColor: colors.accentSoft, borderRadius: 999, color: colors.accent, fontSize: 10, fontWeight: '700', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4, textTransform: 'capitalize' },
  entityStatusDanger: { backgroundColor: '#3a1b22', color: colors.danger },
  entityContext: { color: colors.muted, flex: 1, fontSize: 11 },
  entityMeta: { color: colors.muted, fontSize: 10, fontVariant: ['tabular-nums'] },
  close: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: 4,
  },
  tabs: { gap: 2, paddingHorizontal: spacing.sm },
  tab: {
    borderCurve: 'continuous',
    borderRadius: radii.sm,
    borderWidth: 0,
    minHeight: 32,
    justifyContent: 'center',
    minWidth: 72,
    paddingHorizontal: spacing.sm,
  },
  tabActive: { backgroundColor: colors.surfaceRaised },
  tabText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '500',
    textAlign: 'center',
  },
  tabTextActive: { color: colors.text, fontWeight: '600' },
  content: { gap: spacing.md, padding: spacing.md, paddingBottom: 80 },
  outcome: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    borderLeftWidth: 3,
    gap: 3,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  outcomeTitle: { color: colors.text, fontSize: 12, fontWeight: '800' },
  outcomeText: { color: colors.muted, fontSize: 11, lineHeight: 16 },
  outcomeActive: { backgroundColor: '#111b2b', borderLeftColor: colors.info },
  outcomeSuccess: {
    backgroundColor: '#0d211d',
    borderLeftColor: colors.accent,
  },
  outcomeWarning: {
    backgroundColor: '#261e10',
    borderLeftColor: colors.warning,
  },
  outcomeDanger: { backgroundColor: '#291419', borderLeftColor: colors.danger },
  outcomeNeutral: {
    backgroundColor: colors.surface,
    borderLeftColor: colors.border,
  },
  section: {
    backgroundColor: colors.surface,
    borderCurve: 'continuous',
    borderRadius: radii.lg,
    borderWidth: 0,
    gap: spacing.md,
    overflow: 'hidden',
    padding: spacing.md,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  sectionTitle: { color: colors.text, fontSize: 17, fontWeight: '600' },
  sectionMeta: { color: colors.muted, fontSize: 10 },
  body: { color: colors.text, fontSize: 13, lineHeight: 20 },
  markdown: { minHeight: 20, width: '100%' },
  diffViewer: {
    backgroundColor: '#05070a',
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    height: 560,
    overflow: 'hidden',
  },
  diffNativeView: { flex: 1, width: '100%' },
  changeOverview: { gap: spacing.md },
  changeMetrics: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
  },
  changeMetric: { color: colors.muted, fontSize: 13 },
  changeMetricValue: { color: colors.text, fontSize: 17, fontWeight: '700' },
  filePicker: { gap: spacing.sm, paddingRight: spacing.md },
  fileNavigation: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  fileNavigationButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceRaised,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  fileBrowserButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceRaised,
    borderCurve: 'continuous',
    borderRadius: 18,
    flex: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    height: 36,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  fileBrowserButtonText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '600',
  },
  fileChip: {
    backgroundColor: colors.surfaceRaised,
    borderColor: 'transparent',
    borderCurve: 'continuous',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: 2,
    maxWidth: 190,
    minWidth: 110,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  fileChipSelected: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  fileChipText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  fileChipTextSelected: { color: colors.accent },
  fileChipMeta: { color: colors.muted, fontSize: 9 },
  filePanel: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderCurve: 'continuous',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    overflow: 'hidden',
    padding: spacing.sm,
  },
  filePanelHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
    minHeight: 42,
  },
  filePanelTitle: { flex: 1, gap: 2 },
  fileStatus: { color: colors.muted, fontSize: 9, textTransform: 'uppercase' },
  fileBrowser: { backgroundColor: colors.background, flex: 1 },
  fileSearch: {
    backgroundColor: colors.surfaceRaised,
    borderCurve: 'continuous',
    borderRadius: radii.md,
    color: colors.text,
    fontSize: 16,
    margin: spacing.md,
    minHeight: 42,
    paddingHorizontal: spacing.md,
  },
  fileBrowserList: {
    gap: 2,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xl,
  },
  fileBrowserRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 58,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  fileBrowserRowSelected: { backgroundColor: colors.accentSoft },
  muted: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  label: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
  },
  value: { color: colors.text, fontSize: 13, lineHeight: 18 },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  metric: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.md,
    gap: 3,
    minWidth: 78,
    padding: spacing.sm,
  },
  metricValue: { color: colors.text, fontSize: 16, fontWeight: '800' },
  metricLabel: { color: colors.muted, fontSize: 9, fontWeight: '700' },
  badges: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  badge: {
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    color: colors.accent,
    fontSize: 10,
    fontWeight: '700',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  badgeDanger: { backgroundColor: '#3a1b22', color: colors.danger },
  row: {
    borderTopColor: colors.border,
    borderTopWidth: 1,
    gap: 5,
    paddingTop: spacing.md,
  },
  rowFirst: { borderTopWidth: 0, paddingTop: 0 },
  rowTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  rowText: { color: colors.muted, fontSize: 11, lineHeight: 17 },
  rowMeta: { color: colors.accent, fontSize: 9, fontWeight: '700' },
  eventHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  eventMarker: {
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  eventTitle: { color: colors.text, flex: 1, fontSize: 13, fontWeight: '700' },
  chatTimeline: { gap: spacing.md, paddingVertical: spacing.xs },
  workSessionFlow: { gap: spacing.sm, marginBottom: spacing.md },
  workSession: {
    backgroundColor: colors.surface,
    borderCurve: 'continuous',
    borderRadius: radii.lg,
    marginBottom: spacing.sm,
    overflow: 'hidden',
  },
  workSessionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 52,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  workSessionCopy: { flex: 1, gap: 2 },
  workSessionTitle: { color: colors.text, fontSize: 14, fontWeight: '600' },
  workSessionMeta: { color: colors.muted, fontSize: 10 },
  workSessionContent: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    padding: spacing.md,
  },
  turnChanges: {
    alignSelf: 'flex-end',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderCurve: 'continuous',
    borderRadius: radii.md,
    borderWidth: StyleSheet.hairlineWidth,
    maxWidth: '92%',
    minWidth: 220,
    overflow: 'hidden',
  },
  turnChangesHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing.xs, minHeight: 40, paddingHorizontal: spacing.sm },
  turnChangesTitle: { color: colors.text, flex: 1, fontSize: 12, fontWeight: '600' },
  turnChangesAdditions: { color: colors.success, fontSize: 10, fontVariant: ['tabular-nums'], fontWeight: '700' },
  turnChangesDeletions: { color: colors.danger, fontSize: 10, fontVariant: ['tabular-nums'], fontWeight: '700' },
  turnChangesFiles: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, padding: spacing.sm },
  turnChangesSummary: { color: colors.muted, fontSize: 10, marginBottom: spacing.xs },
  turnChangesFile: { alignItems: 'center', flexDirection: 'row', gap: spacing.xs, minHeight: 30 },
  turnChangesPath: { color: colors.text, flex: 1, fontFamily: 'Menlo', fontSize: 10 },
  chatEmpty: { alignItems: 'center', paddingVertical: spacing.xl },
  toolCall: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 36,
    paddingHorizontal: spacing.xs,
  },
  toolCallTitle: {
    color: colors.muted,
    flex: 1,
    fontSize: 12,
    fontWeight: '500',
  },
  toolCallMeta: { color: colors.muted, fontSize: 10 },
  chatMessageRow: { alignItems: 'flex-start', width: '100%' },
  chatMessageRowUser: { alignItems: 'flex-end' },
  chatMessage: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderBottomLeftRadius: spacing.xs,
    borderWidth: 1,
    gap: spacing.sm,
    maxWidth: '92%',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  chatMessageUser: {
    alignSelf: 'flex-end',
    backgroundColor: colors.accent,
    borderBottomLeftRadius: radii.lg,
    borderBottomRightRadius: spacing.xs,
    borderColor: colors.accent,
    flexShrink: 1,
    maxWidth: '88%',
  },
  chatAssistantMessage: { maxWidth: '100%', width: '100%' },
  chatMessageTextAssistant: { color: colors.text, fontSize: 15, lineHeight: 22, width: '100%' },
  chatMessageTextUser: { color: '#ffffff', fontSize: 15, lineHeight: 21 },
  chatMessageActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    marginTop: 2,
  },
  chatMessageActionsUser: { justifyContent: 'flex-end' },
  chatMessageTime: { color: colors.muted, fontSize: 10 },
  chatMessageCopy: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 24,
    minWidth: 24,
  },
  chatMessageSystem: {
    backgroundColor: colors.surfaceRaised,
    borderBottomLeftRadius: radii.lg,
    maxWidth: '100%',
  },
  chatMessageHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  chatMessageAuthor: { color: colors.accent, fontSize: 10, fontWeight: '800' },
  chatMessageAuthorUser: { color: colors.text },
  chatMessageMeta: {
    color: colors.muted,
    flexShrink: 1,
    fontSize: 9,
    textAlign: 'right',
  },
  queueCard: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.md,
    gap: spacing.sm,
    padding: spacing.md,
  },
  fileRow: {
    alignItems: 'center',
    borderTopColor: colors.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  filePath: {
    color: colors.text,
    flex: 1,
    fontFamily: 'monospace',
    fontSize: 11,
  },
  additions: { color: colors.accent, fontSize: 10, fontWeight: '700' },
  deletions: { color: colors.danger, fontSize: 10, fontWeight: '700' },
  code: {
    backgroundColor: '#05070a',
    borderRadius: radii.md,
    color: '#c7d2df',
    fontFamily: 'monospace',
    fontSize: 10,
    lineHeight: 15,
    padding: spacing.md,
  },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  actionsSpread: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  primaryButtonText: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  secondaryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  secondaryButtonText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '700',
  },
  dangerButton: { borderColor: colors.danger },
  dangerButtonText: { color: colors.danger },
  input: {
    backgroundColor: colors.surfaceRaised,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    color: colors.text,
    fontSize: 13,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingVertical: 11,
  },
  textarea: { minHeight: 100, textAlignVertical: 'top' },
  compactTextarea: { minHeight: 72, textAlignVertical: 'top' },
  footer: {
    backgroundColor: colors.background,
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingBottom: spacing.sm,
    paddingTop: 6,
  },
  composerFrame: {
    gap: spacing.xs,
  },
  composerRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  composerControlsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  composerContextRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  composerMachineGlass: {
    borderCurve: 'continuous',
    borderRadius: radii.lg,
    maxWidth: 132,
    minHeight: 44,
    overflow: 'hidden',
  },
  composerMachine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  composerMachineText: { color: colors.muted, flexShrink: 1, fontSize: 11, fontWeight: '600' },
  composerInputGlass: {
    borderCurve: 'continuous',
    borderRadius: 22,
    flex: 1,
    minHeight: 44,
    overflow: 'hidden',
  },
  composerPasteWrapper: { flex: 1 },
  composerVoiceActive: { backgroundColor: `${colors.danger}18` },
  composerVoicePreview: { color: colors.muted, fontSize: 12, paddingHorizontal: spacing.sm },
  composerModelProgress: { gap: 5, paddingHorizontal: spacing.sm, paddingVertical: 4 },
  composerModelProgressHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  composerModelProgressLabel: { color: colors.text, fontSize: 11, fontWeight: '600' },
  composerModelProgressValue: { color: colors.accent, fontSize: 11, fontVariant: ['tabular-nums'], fontWeight: '700' },
  composerModelProgressTrack: { backgroundColor: colors.surfaceRaised, borderRadius: 2, height: 4, overflow: 'hidden' },
  composerModelProgressFill: { backgroundColor: colors.accent, borderRadius: 2, height: '100%' },
  composerModelProgressHint: { color: colors.muted, fontSize: 9 },
  composerInput: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    flex: 1,
    fontSize: 16,
    lineHeight: 20,
    maxHeight: 120,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingBottom: 12,
    paddingTop: 12,
    textAlignVertical: 'center',
  },
  composerControlGlass: {
    borderCurve: 'continuous',
    borderRadius: 22,
    height: 44,
    overflow: 'hidden',
    width: 44,
  },
  composerConfigGlass: {
    borderCurve: 'continuous',
    borderRadius: 22,
    flex: 1,
    height: 44,
    overflow: 'hidden',
  },
  composerConfigButton: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 22,
    flex: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    height: 44,
    paddingHorizontal: spacing.md,
  },
  composerConfigCopy: { flex: 1 },
  composerConfigTitle: { color: colors.text, fontSize: 12, fontWeight: '600' },
  composerConfigMeta: { color: colors.muted, fontSize: 9 },
  composerIconButton: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  composerSendButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderCurve: 'continuous',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  attachmentList: { gap: spacing.sm, padding: spacing.xs },
  attachmentPreview: {
    borderRadius: radii.sm,
    height: 52,
    overflow: 'hidden',
    width: 52,
  },
  attachmentImage: { height: '100%', width: '100%' },
  attachmentRemove: {
    backgroundColor: 'rgba(0,0,0,0.65)',
    borderRadius: 10,
    position: 'absolute',
    right: 2,
    top: 2,
  },
  headerIconButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    minWidth: 72,
    paddingHorizontal: spacing.sm,
  },
  composerMeta: { color: colors.muted, flex: 1, fontSize: 10, lineHeight: 14 },
  footerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'flex-end',
  },
  footerButton: { flex: 1 },
  actionModal: { backgroundColor: colors.background, flex: 1 },
  actionModalHeader: {
    alignItems: 'flex-start',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.lg,
  },
  actionModalContent: {
    gap: spacing.md,
    padding: spacing.lg,
    paddingBottom: spacing.xl,
  },
  actionList: { gap: spacing.sm },
  actionOption: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 50,
    padding: spacing.md,
  },
  actionOptionCopy: { flex: 1, gap: 2 },
  actionOptionTitle: { color: colors.text, fontSize: 13, fontWeight: '800' },
  actionOptionText: { color: colors.muted, fontSize: 10, lineHeight: 15 },
  optionSelected: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  formGroup: { gap: spacing.sm },
  inputLabel: { color: colors.text, fontSize: 12, fontWeight: '800' },
  inputHint: { color: colors.muted, fontSize: 10, lineHeight: 15 },
  suggestion: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.md,
    gap: spacing.sm,
    padding: spacing.md,
  },
  suggestionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  error: { color: colors.danger, fontSize: 12, lineHeight: 17 },
  notice: { color: colors.accent, fontSize: 12, lineHeight: 17 },
  state: {
    alignItems: 'center',
    flex: 1,
    gap: spacing.sm,
    justifyContent: 'center',
    padding: spacing.xl,
  },
  stateTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
  stateText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.7 },
})
