import { StyleSheet } from 'react-native'
import { colors, radii, spacing } from '@/theme'

export const mobileWorkspaceStyles = StyleSheet.create({
  screen: { backgroundColor: colors.background, flex: 1 },
  completionHud: { borderCurve: 'continuous', borderRadius: radii.lg, left: spacing.md, overflow: 'hidden', position: 'absolute', right: spacing.md, top: spacing.sm, zIndex: 100 },
  completionHudOpen: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, minHeight: 64, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  completionHudCopy: { flex: 1, gap: 2 },
  completionHudLabel: { color: colors.accent, fontSize: 11, fontWeight: '700' },
  completionHudTitle: { color: colors.text, fontSize: 15, fontWeight: '600' },
  header: { gap: spacing.sm, paddingHorizontal: spacing.md, paddingTop: spacing.xs, paddingBottom: spacing.sm },
  topRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  heading: { flex: 1, gap: 3 },
  eyebrow: { color: colors.muted, fontSize: 10, fontWeight: '700', letterSpacing: 1.2 },
  title: { color: colors.text, fontSize: 34, fontWeight: '700', letterSpacing: -1, lineHeight: 41 },
  subtitle: { color: colors.muted, flexShrink: 1, fontSize: 13, lineHeight: 18 },
  createButton: { alignItems: 'center', backgroundColor: colors.accent, borderCurve: 'continuous', borderRadius: 20, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 40, paddingHorizontal: spacing.md },
  createButtonText: { color: colors.ink, fontSize: 15, fontWeight: '600' },
  search: { backgroundColor: colors.surfaceRaised, borderRadius: radii.md, color: colors.text, fontSize: 17, minHeight: 44, paddingHorizontal: spacing.md, paddingVertical: 10 },
  list: { gap: 10, paddingHorizontal: spacing.md, paddingTop: spacing.sm, paddingBottom: spacing.xl },
  statusBox: { backgroundColor: colors.surface, borderCurve: 'continuous', borderRadius: radii.lg, gap: spacing.sm, overflow: 'hidden', padding: spacing.md },
  notice: { color: colors.accent, fontSize: 12, lineHeight: 17 },
  error: { color: colors.danger, fontSize: 12, lineHeight: 17 },
  card: { backgroundColor: colors.surface, borderCurve: 'continuous', borderRadius: radii.lg, gap: 7, overflow: 'hidden', paddingHorizontal: spacing.md, paddingVertical: 13 },
  cardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' },
  cardAccessory: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  cardCopy: { flex: 1, gap: 4 },
  cardEyebrow: { color: colors.accent, fontSize: 10, fontWeight: '600', letterSpacing: 0.7 },
  cardTitle: { color: colors.text, fontSize: 17, fontWeight: '600', lineHeight: 22 },
  cardText: { color: colors.muted, fontSize: 15, lineHeight: 20 },
  badge: { alignSelf: 'flex-start', backgroundColor: colors.accentSoft, borderRadius: 999, color: colors.accent, fontSize: 10, fontWeight: '800', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4 },
  badgeDanger: { backgroundColor: '#3a1b22', color: colors.danger },
  metadata: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  cardActions: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  primaryButton: { alignItems: 'center', backgroundColor: colors.accent, borderCurve: 'continuous', borderRadius: radii.md, justifyContent: 'center', minHeight: 40, paddingHorizontal: spacing.md },
  primaryButtonText: { color: colors.ink, fontSize: 14, fontWeight: '600' },
  secondaryButton: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: colors.surfaceRaised, borderCurve: 'continuous', borderRadius: radii.sm, justifyContent: 'center', minHeight: 34, paddingHorizontal: spacing.sm },
  secondaryButtonText: { color: colors.accent, fontSize: 14, fontWeight: '600' },
  empty: { alignItems: 'center', gap: spacing.sm, minHeight: 220, justifyContent: 'center', padding: spacing.xl },
  emptyTitle: { color: colors.text, fontSize: 16, fontWeight: '800', textAlign: 'center' },
  emptyText: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: 'center' },
  more: { gap: spacing.lg },
  sectionTitle: { color: colors.text, fontSize: 22, fontWeight: '700' },
  modal: { backgroundColor: colors.background, flex: 1 },
  modalHeader: { alignItems: 'flex-start', borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between', padding: spacing.md },
  modalHeading: { flex: 1, gap: 4 },
  modalEyebrow: { color: colors.accent, fontSize: 10, fontWeight: '800', letterSpacing: 1.5 },
  modalTitle: { color: colors.text, fontSize: 24, fontWeight: '800' },
  close: { color: colors.accent, fontSize: 14, fontWeight: '700' },
  modalContent: { gap: spacing.md, padding: spacing.md, paddingBottom: spacing.xl },
  creationSection: { gap: spacing.sm, paddingVertical: spacing.xs },
  localFolderButton: { alignItems: 'center', alignSelf: 'flex-start', borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, minHeight: 40, paddingHorizontal: spacing.md },
  localFolderButtonText: { color: colors.accent, fontSize: 15, fontWeight: '600' },
  localFolderPicker: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: spacing.sm, padding: spacing.md },
  localFolderHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  linkText: { color: colors.accent, fontSize: 15, fontWeight: '600' },
  monospaceInput: { fontFamily: 'Menlo', fontSize: 13 },
  folderActions: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  compactButton: { backgroundColor: colors.surfaceRaised, borderRadius: radii.sm, minHeight: 34, paddingHorizontal: spacing.md, justifyContent: 'center' },
  compactButtonText: { color: colors.accent, fontSize: 14, fontWeight: '600' },
  folderList: { backgroundColor: colors.surfaceRaised, borderRadius: radii.md, maxHeight: 210 },
  folderRow: { alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', gap: spacing.sm, minHeight: 44, paddingHorizontal: spacing.md },
  folderRowText: { color: colors.text, flex: 1, fontSize: 15 },
  creationStep: { color: colors.accent, fontSize: 10, fontWeight: '800', letterSpacing: 1.1 },
  inputGroup: { gap: spacing.sm },
  inputLabel: { color: colors.text, fontSize: 13, fontWeight: '800' },
  inputHint: { color: colors.muted, fontSize: 11, lineHeight: 16 },
  textArea: { minHeight: 120, textAlignVertical: 'top' },
  options: { gap: spacing.sm },
  option: { backgroundColor: colors.surfaceRaised, borderColor: 'transparent', borderCurve: 'continuous', borderRadius: radii.md, borderWidth: 1, gap: 3, minHeight: 56, paddingHorizontal: spacing.md, paddingRight: 48, paddingVertical: 10, position: 'relative' },
  connectionNameInput: { color: colors.text, fontSize: 15, fontWeight: '700', paddingVertical: 4 },
  optionSelected: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  optionAccessory: { alignItems: 'center', justifyContent: 'center', position: 'absolute', right: spacing.md, top: 17 },
  optionText: { color: colors.text, fontSize: 13, fontWeight: '700' },
  optionTextSelected: { color: colors.accent },
  optionMeta: { color: colors.muted, fontSize: 10 },
  switchRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  switchCopy: { flex: 1, gap: 3 },
  disclosure: { backgroundColor: colors.surface, borderColor: colors.border, borderCurve: 'continuous', borderRadius: radii.lg, borderWidth: StyleSheet.hairlineWidth, overflow: 'hidden' },
  disclosureHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, minHeight: 62, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  disclosureIcon: { alignItems: 'center', backgroundColor: colors.accentSoft, borderCurve: 'continuous', borderRadius: radii.sm, height: 34, justifyContent: 'center', width: 34 },
  disclosureCopy: { flex: 1, gap: 2 },
  disclosureTitle: { color: colors.text, fontSize: 15, fontWeight: '600' },
  disclosureSummary: { color: colors.muted, fontSize: 11, lineHeight: 15 },
  disclosureContent: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, gap: spacing.md, padding: spacing.md },
  disclosureBody: { gap: spacing.sm },
  modalFooter: { backgroundColor: colors.glassStrong, borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, gap: spacing.sm, paddingHorizontal: spacing.md, paddingTop: spacing.sm },
  modalFooterSummary: { color: colors.muted, fontSize: 11, textAlign: 'center' },
  modalPrimary: { alignItems: 'center', backgroundColor: colors.accent, borderCurve: 'continuous', borderRadius: radii.md, justifyContent: 'center', minHeight: 50 },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.72 },
})
