import { StyleSheet } from 'react-native'
import { colors, radii, spacing } from '@/theme'

export const portableCollectionStyles = StyleSheet.create({
  screen: { backgroundColor: colors.background, flex: 1 },
  header: { borderBottomColor: colors.border, borderBottomWidth: 1, gap: spacing.sm, padding: spacing.md },
  eyebrow: { color: colors.accent, fontSize: 10, fontWeight: '800', letterSpacing: 1.5 },
  title: { color: colors.text, fontSize: 25, fontWeight: '800', letterSpacing: -0.6 },
  subtitle: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  search: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.text, fontSize: 14, paddingHorizontal: spacing.md, paddingVertical: 11 },
  row: { flexDirection: 'row', gap: spacing.sm },
  chips: { gap: spacing.sm },
  chip: { backgroundColor: colors.surfaceRaised, borderCurve: 'continuous', borderRadius: radii.sm, minHeight: 32, justifyContent: 'center', paddingHorizontal: spacing.md, paddingVertical: 6 },
  chipActive: { backgroundColor: colors.accent },
  chipText: { color: colors.muted, fontSize: 13, fontWeight: '500' },
  chipTextActive: { color: colors.ink, fontWeight: '600' },
  list: { gap: spacing.sm, padding: spacing.md, paddingBottom: 50 },
  board: { alignItems: 'flex-start', gap: spacing.md, padding: spacing.md },
  column: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, maxHeight: '100%', width: 290 },
  columnHeader: { alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between', padding: spacing.md },
  columnTitle: { color: colors.text, flex: 1, fontSize: 13, fontWeight: '800' },
  count: { backgroundColor: colors.surfaceRaised, borderRadius: 999, color: colors.muted, fontSize: 11, overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 3 },
  columnItems: { gap: spacing.sm, padding: spacing.sm },
  card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: spacing.md, padding: spacing.md },
  cardCompact: { backgroundColor: colors.surfaceRaised },
  cardTitle: { color: colors.text, fontSize: 16, fontWeight: '800', lineHeight: 21 },
  fields: { gap: spacing.md },
  field: { gap: 4 },
  fieldName: { color: colors.muted, fontSize: 9, fontWeight: '800', letterSpacing: 1 },
  fieldValue: { color: colors.text, fontSize: 13, lineHeight: 18 },
  badge: { alignSelf: 'flex-start', backgroundColor: colors.accentSoft, borderRadius: 999, color: colors.accent, fontSize: 11, fontWeight: '700', overflow: 'hidden', paddingHorizontal: 9, paddingVertical: 4 },
  person: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  avatar: { backgroundColor: colors.accentSoft, borderRadius: 999, color: colors.accent, fontSize: 10, fontWeight: '800', overflow: 'hidden', padding: 8 },
  avatarImage: { borderRadius: 999, height: 28, width: 28 },
  relations: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  relation: { alignItems: 'center', borderColor: colors.border, borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 6, maxWidth: 190, overflow: 'hidden', paddingBottom: 3, paddingLeft: 3, paddingRight: 8, paddingTop: 3 },
  relationText: { color: colors.text, flexShrink: 1, fontSize: 11 },
  cardActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, justifyContent: 'flex-end' },
  primaryButton: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: radii.md, justifyContent: 'center', minHeight: 40, paddingHorizontal: spacing.md },
  primaryButtonText: { color: colors.ink, fontSize: 13, fontWeight: '800' },
  secondaryButton: { alignItems: 'center', borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, justifyContent: 'center', minHeight: 40, paddingHorizontal: spacing.md },
  secondaryButtonText: { color: colors.text, fontSize: 13, fontWeight: '700' },
  modal: { backgroundColor: colors.background, flex: 1 },
  modalHeader: { alignItems: 'flex-start', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: spacing.lg },
  modalHeading: { flex: 1, gap: 4, paddingRight: spacing.md },
  modalEyebrow: { color: colors.accent, fontSize: 10, fontWeight: '800', letterSpacing: 1.5 },
  modalTitle: { color: colors.text, fontSize: 24, fontWeight: '800' },
  close: { color: colors.accent, fontSize: 14, fontWeight: '700' },
  modalContent: { gap: spacing.lg, padding: spacing.md, paddingBottom: spacing.xl },
  detailGroup: { gap: spacing.sm },
  detailBox: { borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, gap: spacing.sm, padding: spacing.md },
  modalPrimary: { alignItems: 'center', backgroundColor: colors.accent, borderCurve: 'continuous', borderRadius: radii.md, justifyContent: 'center', margin: spacing.md, minHeight: 50 },
  modalActions: { paddingBottom: spacing.lg },
  inputGroup: { gap: spacing.sm },
  inputLabel: { color: colors.text, fontSize: 13, fontWeight: '800' },
  booleanInput: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  switchRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  switchCopy: { flex: 1, gap: 3 },
  optionList: { gap: spacing.sm },
  option: { borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, padding: spacing.md },
  optionSelected: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  optionText: { color: colors.text, fontSize: 13 },
  optionTextSelected: { color: colors.accent, fontWeight: '800' },
  error: { color: colors.danger, fontSize: 12, lineHeight: 17 },
  textarea: { minHeight: 120, textAlignVertical: 'top' },
  workflowResult: { fontFamily: 'monospace', minHeight: 300, textAlignVertical: 'top' },
  state: { alignItems: 'center', flex: 1, gap: spacing.sm, justifyContent: 'center', minHeight: 220, padding: spacing.xl },
  stateTitle: { color: colors.text, fontSize: 16, fontWeight: '800', textAlign: 'center' },
  stateText: { color: colors.muted, fontSize: 13, lineHeight: 19, textAlign: 'center' },
  disabled: { opacity: 0.5 },
  pressed: { opacity: 0.7 },
})
