import { StyleSheet } from 'react-native'
import { colors, radii, spacing } from '@/theme'

export const portableSettingsStyles = StyleSheet.create({
  content: { gap: spacing.md, padding: spacing.md, paddingBottom: spacing.xl },
  header: { gap: spacing.xs },
  title: { color: colors.text, fontSize: 22, fontWeight: '800' },
  description: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  section: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: spacing.md, padding: spacing.md },
  sectionTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
  field: { gap: spacing.xs },
  fieldLabel: { color: colors.text, fontSize: 13, fontWeight: '700' },
  input: { backgroundColor: colors.surfaceRaised, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.text, fontSize: 14, minHeight: 44, paddingHorizontal: spacing.md, paddingVertical: 10 },
  textarea: { minHeight: 110, textAlignVertical: 'top' },
  switchRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  choice: { borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, paddingHorizontal: spacing.sm, paddingVertical: 8 },
  choiceActive: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  choiceText: { color: colors.muted, fontSize: 12 },
  choiceTextActive: { color: colors.accent, fontWeight: '700' },
  disabled: { opacity: 0.45 },
  objectCard: { backgroundColor: colors.surfaceRaised, borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, gap: spacing.md, padding: spacing.md },
  row: { alignItems: 'center', flexDirection: 'row', gap: spacing.xs },
  flex: { flex: 1 },
  smallButton: { borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, paddingHorizontal: spacing.sm, paddingVertical: 9 },
  smallButtonText: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  secondaryButton: { alignItems: 'center', borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, justifyContent: 'center', minHeight: 42, paddingHorizontal: spacing.md },
  secondaryButtonText: { color: colors.text, fontSize: 13, fontWeight: '700' },
  primaryButton: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: radii.md, flex: 1, justifyContent: 'center', minHeight: 46, paddingHorizontal: spacing.md },
  primaryButtonText: { color: colors.ink, fontSize: 13, fontWeight: '800' },
  dangerButton: { alignItems: 'center', borderColor: colors.danger, borderRadius: radii.md, borderWidth: 1, justifyContent: 'center', minHeight: 46, paddingHorizontal: spacing.md },
  dangerButtonText: { color: colors.danger, fontSize: 13, fontWeight: '800' },
  dangerText: { color: colors.danger, fontSize: 11, fontWeight: '700' },
  footer: { flexDirection: 'row', gap: spacing.sm },
  state: { alignItems: 'center', flex: 1, gap: spacing.sm, justifyContent: 'center', padding: spacing.xl },
  error: { color: colors.danger, fontSize: 12, lineHeight: 18 },
  success: { color: colors.accent, fontSize: 12, lineHeight: 18 },
})
