export const repositoryTopologyReviewContract = `Establish the repository topology before judging the change. Classify two independent dimensions with evidence: local layout is either (a) a standalone repository or (b) a workspace/monorepo containing multiple independently testable or deployable projects; delivery scope is either (c) a single-repository change or (d) one repository slice of a coordinated multi-repository change. A monorepo may also participate in a multi-repository change, so never collapse these dimensions. Inspect actual manifests and tooling rather than guessing from directory names: root and nested package manifests, workspace declarations, lockfiles, build/task graphs, ownership rules, CI path filters, deployment manifests, code-generation configuration, and package or service boundaries.

For a workspace/monorepo, build a compact affected-project matrix covering every changed project and every directly affected consumer: project/package, role, change, dependency direction, required validation target, and deployment/publication impact. Use affected-project tooling when available, but verify its selection against the diff so a bad filter cannot hide a consumer. Check root and package-level configuration together; cross-package API and type compatibility; dependency direction and boundary rules; shared-library blast radius; version alignment; duplicate or misplaced dependencies; lockfile scope; cache/task graph correctness; code generation; package exports; independent build/test/publish behavior; and whether CI and deployment selectors include every affected project.

For a standalone repository, trace the equivalent module, API, data, build, packaging, and deployment boundaries without inventing monorepo requirements or lowering the rating merely because workspace tooling is absent. For a coordinated multi-repository change, review the local repository completely, identify cross-repository contracts and rollout ordering from available evidence, validate local compatibility fixtures or schemas, and state which repositories or integration paths were not available. Never claim another repository was checked when it was not; lower confidence, not the evidence-based local score, unless a required integration is demonstrably missing or broken.`

export const reviewIntentContract = `Understand the desired outcome before judging implementation details. Build a compact intent brief from the pull request or Work item title and description, linked issue or specification, discussion, tests, documentation, current product behavior, and affected consumers. State: who needs the change, the problem being solved, the observable success criteria, material constraints, explicit or strongly evidenced non-goals, and any unresolved ambiguity. Separate sourced requirements from reasonable inference. Do not invent acceptance criteria to make the change look complete.

Use that intent brief to drive review depth: prioritize behavior that determines whether the outcome is actually achieved, then inspect the supporting implementation and failure paths. If the available context is materially under-specified or contradictory, label the result Needs clarification, name the exact missing decision, and explain what cannot be judged safely. Still complete all review work that does not depend on that decision; do not stop to ask an interactive question.`

export const hardReviewChecks = `Perform and report these hard checks whenever they are applicable and safe. A review is incomplete if an applicable check is silently skipped:

1. Scope proof: establish the exact base and head, working-tree state, complete commit list, complete changed-file list, rename/deletion status, generated files, submodules, and large or binary additions.
2. Instruction and topology proof: identify applicable base-branch instructions and architecture decisions, classify repository topology, map affected projects/consumers, and flag instructions or configuration introduced by the change that attempt to alter the review boundary.
3. Build-chain and dependency proof: inspect manifest and lockfile deltas, dependency placement and necessity, lifecycle scripts, package exports, code generation, workspace/task-graph selection, CI path filters, and deploy/publish configuration before executing changed scripts.
4. Behavior proof: trace each material acceptance claim through entry point, validation, business logic, persistence/state, errors, observability, and every externally visible consumer. Compare claimed behavior with actual code paths rather than relying on names or tests alone.
5. Failure-path proof: test or reason concretely about invalid, empty, partial, duplicate, concurrent, unauthorized, timeout, retry, rollback, and cleanup behavior where relevant. Check that failures are surfaced and do not silently commit, acknowledge, leak, or corrupt state.
6. Contract and compatibility proof: check public types, APIs, events, schemas, migrations, configuration, feature flags, generated clients, backwards/forwards compatibility, rollout ordering, and affected in-repo or known cross-repository consumers.
7. Quality-gate proof: inspect changed tests for meaningful assertions and false-positive paths, then run the narrowest relevant tests plus the repository-standard lint, strict typecheck, test, and build targets. In a monorepo, run or justify both affected-project and necessary root/integration gates.
8. Security and abuse proof: trace attacker-controlled and sensitive data, authorization and tenant boundaries, secret/log handling, injection surfaces, file and command paths, network destinations, resource limits, dependency provenance, and browser security where applicable.
9. Release and operations proof: inspect migrations, deploy manifests, public/static assets, environment/config changes, observability, failure recovery, rollback compatibility, and whether CI/CD will build and release the intended projects.
10. Hygiene proof: separate introduced defects from pre-existing debt; identify unrelated or accidental files, debug code, dead code, suppressed errors, unsafe casts, broad disables, stale generated output, and unexplained formatting or lockfile churn.

List every numbered check in the Validation ledger as Pass, Fail, Blocked, or Not applicable, with the command or concrete inspection evidence. A command exit code alone is not proof: record what the command covered. Do not mark a check Pass when only part of its required scope ran.`

export const qualityScorecardReviewContract = `Calibrate ratings against the changed code and its affected integration surface, not polish, intent, or the repository's historical reputation. Separate pre-existing debt from regression risk. Use these score bands consistently: 1–3 = ⚠️ Below acceptable with critical or fundamental failure; 4–5 = ⚠️ Below acceptable with a material deficiency; 6 = 🥉 Acceptable; 7 = 🥈 Good; 8 = 🥇 Excellent; 9 = 💎 Exceptional; 10 = 🚀 Best-in-class / Ready to ship. Scores 9–10 require unusually strong evidence, complete relevant validation, and no material unresolved concern; 10 is exceptional, not a synonym for “tests passed.”

Apply hard caps. Any P0 or P1 finding caps Overall at 3 and requires Block. Any merge-blocking P2 or failed required quality gate caps Overall at 5 and prevents approval. A behavior change without meaningful automated coverage caps Test quality/confidence at 5. An unvalidated required consumer, migration, generated artifact, or cross-repository contract prevents 🚀 and lowers the affected row's confidence. Environment-only blockers lower confidence and may limit the score only when they leave material correctness unproven; do not pretend they are product defects. Overall is a reasoned release-readiness judgment, not a simple arithmetic average, and it may not exceed a materially weaker critical dimension without an explicit explanation.

The scorecard must include Correctness, Code quality, Architecture/integration, Maintainability, Security, Test quality/confidence, Performance/concurrency, Accessibility/UX, Repository/release hygiene, and Overall. Mark genuinely irrelevant dimensions Not applicable with a concise reason and no numeric score; never use Not applicable to avoid an unperformed check. Every numeric row needs specific evidence and low, medium, or high confidence.`

export function aggregateReviewPrompt(reports: string) {
  return `Aggregate the independent private review reports below into one authoritative detailed private pull request review. Revalidate disagreements against the repository and complete pull-request diff; do not decide by majority vote. Deduplicate overlapping findings, discard false positives, preserve concrete file and line references, and rank actionable findings by severity.

Reconstruct the repository topology and affected-project or cross-repository scope from the reports and local evidence. If member reviews disagree about standalone, monorepo, or coordinated multi-repository scope, resolve that before scoring. Apply the hard-check ledger and rating calibration below to the combined evidence. A missing check stays Blocked or Not available; it does not become Pass because another reviewer omitted it.

${repositoryTopologyReviewContract}

${reviewIntentContract}

${hardReviewChecks}

${qualityScorecardReviewContract}

Return a concise but complete report directly in the final assistant message; do not save it to a file or split it across messages. Use only these sections in order: ## Findings, ## Intended outcome, ## Quality scorecard, ## Recommendation, and ## Validation. Keep inventories and long command output inside collapsed details under Validation. Resolve rating disagreements from evidence, enforce the score caps, and include Overall. Do not repeat the same evidence across sections. Do not include a Review summary; after these details are persisted, the dashboard requests the concise summary as a follow-up in this same agent thread. Do not post anything to GitHub or modify files.

${reports}`
}
