import { definePortableSettings } from '@vertexade/platform-extension-sdk'

export const githubSettings = definePortableSettings({
  id: 'settings',
  title: 'GitHub and deployments',
  description: 'Configure authentication and one or more GitHub Actions deployment targets for this server.',
  source: { path: '/settings', configuredPath: 'connected' },
  fields: [
    { name: 'active', label: 'Use GitHub App authentication', type: 'boolean' },
    {
      name: 'app_id',
      label: 'App ID',
      type: 'text',
      required: true,
      visibleWhen: { input: 'active', equals: true },
    },
    {
      name: 'installation_id',
      label: 'Installation ID',
      type: 'text',
      required: true,
      visibleWhen: { input: 'active', equals: true },
    },
    {
      name: 'private_key',
      label: 'Private key',
      type: 'textarea',
      required: true,
      storedPath: 'has_private_key',
      visibleWhen: { input: 'active', equals: true },
      placeholder: '-----BEGIN PRIVATE KEY-----',
    },
    {
      name: 'deployment_targets',
      label: 'Deployment targets',
      type: 'object-list',
      valuePath: 'deployment_targets',
      addLabel: 'Add deployment target',
      allowReorder: true,
      maxItems: 20,
      description: 'Each target is queried independently and appears as a labeled group on Delivery.',
      fields: [
        {
          name: 'id',
          label: 'Stable id',
          type: 'text',
          required: true,
          description: 'A permanent id used to route reruns even if the label changes.',
        },
        { name: 'label', label: 'Label', type: 'text', required: true },
        {
          name: 'enabled',
          label: 'Enabled',
          type: 'boolean',
          defaultValue: true,
          description: 'Disabled targets remain configured but are not queried.',
        },
        {
          name: 'repository',
          label: 'Repository',
          type: 'text',
          required: true,
          placeholder: 'owner/repository',
          description: 'The GitHub owner/repository containing the workflow.',
        },
        {
          name: 'workflow',
          label: 'Workflow',
          type: 'text',
          required: true,
          placeholder: 'deploy.yml',
          description: 'A workflow file name or numeric GitHub workflow id.',
        },
        { name: 'branch', label: 'Branch', type: 'text', required: true, defaultValue: 'main', placeholder: 'main' },
        {
          name: 'event',
          label: 'Workflow event',
          type: 'select',
          required: true,
          defaultValue: 'push',
          options: [
            { value: 'push', label: 'Push' },
            { value: 'workflow_dispatch', label: 'Manual dispatch' },
            { value: 'schedule', label: 'Schedule' },
            { value: 'pull_request', label: 'Pull request' },
            { value: 'release', label: 'Release' },
          ],
          description: 'Only runs triggered by this GitHub event are included.',
        },
        {
          name: 'services',
          label: 'Services',
          type: 'string-list',
          description: 'Optional seed list. Services found in matching job names are added automatically.',
        },
        {
          name: 'environments',
          label: 'Environment ids',
          type: 'string-list',
          required: true,
          minItems: 1,
          defaultValue: ['dev', 'acc', 'prd'],
          description: 'Ordered environment ids captured from job names, for example dev, acc, and prd.',
        },
        {
          name: 'comparison_environment',
          label: 'Comparison environment',
          type: 'text',
          required: true,
          defaultValue: 'dev',
          description: 'The leading environment compared against production to detect an outdated release.',
        },
        {
          name: 'production_environment',
          label: 'Production environment',
          type: 'text',
          required: true,
          defaultValue: 'prd',
          description: 'The terminal environment used for deployed state and pending commit calculations.',
        },
        {
          name: 'job_name_template',
          label: 'Job name template',
          type: 'text',
          required: true,
          defaultValue: 'Build and deploy service - {service} / Deploy {*} -> {environment}',
          placeholder: 'Build and deploy service - {service} / Deploy {*} -> {environment}',
          description:
            'Use {service} and {environment} exactly once. {*} safely matches variable text without accepting a free-form regular expression.',
        },
      ],
    },
  ],
  sections: [
    {
      id: 'authentication',
      title: 'Authentication',
      description: 'Use the existing gh authentication or encrypted GitHub App installation credentials.',
      fields: ['active', 'app_id', 'installation_id', 'private_key'],
    },
    {
      id: 'deployments',
      title: 'GitHub Actions deployments',
      description: 'Targets, workflows, services, environments, and job matching are managed independently on this server.',
      fields: ['deployment_targets'],
    },
  ],
  submit: {
    method: 'POST',
    path: '/settings',
    label: 'Save GitHub settings',
    successMessage: 'GitHub authentication and deployment targets saved.',
  },
  actions: [
    {
      id: 'reset',
      label: 'Remove app credentials',
      method: 'DELETE',
      path: '/settings',
      intent: 'reset',
      confirm: {
        title: 'Remove GitHub App credentials?',
        description:
          'The encrypted installation credentials will be deleted and gh authentication will be used. Deployment targets are retained.',
        confirmLabel: 'Remove credentials',
        destructive: true,
      },
    },
  ],
})
